openapi: 3.0.1
info:
  title: Delailah Resto
  description: priemera API de un Resto
  version: 0.1.9
servers:
  - url: http://localhost:9080/api/v1
    description: Optional server description, e.g. Main (production) server

paths:
  #/auth:
   # get:
    #  parameters:
     #   - name: token
      #      in: header
       #     description: token to be passed as a header
        #    required: 
         #     schema:
          #      type: string

     # summary: Returns a list of users. describir que hace ese get
      #description: endpoint para...bla bla bla
       #responses:
        #"200": # status code
         # description: its OK , A JSON array of user names
          #content:
           # application/json:
            #  schema:
             #   type: array
              #  items:
               #   type: string

  /productos:
    get:
      summary: Returns a list of users. describir que hace ese get
      description: endpoint para...bla bla bla
      responses:
        "200": # status code
          description: its OK , A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /pedidos:
    get:
      summary: Returns a list of users. describir que hace ese get
      description: endpoint para...bla bla bla
      responses:
        "200": # status code
          description: its OK , A JSON array of user names
          content:
            application/json:
              schema:
                type: array

  /users:
    get:
      summary: Returns a list of users. describir que hace ese get
      description: endpoint para...bla bla bla
      responses:
        "200": # status code
          description: its OK , A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
